// Autogenerated by Nightwatch
// Refer to the online docs for more details: https://nightwatchjs.org/gettingstarted/configuration/
const Services = {}; loadServices();

module.exports = {
  src_folders: ['tests'],
  custom_commands_path:  'commands',
  webdriver: {
    // ローカルのwebdriverを起動しないようにする
    "start_process" : false
  },

  test_settings: {
    seleniumA: {
      desiredCapabilities: {
        browserName : 'chrome',
        chromeOptions : {
          w3c : false
        }      
      },
      // リモートのwebdriverのipとportを指定する
      selenium_port :14444,
      selenium_host : "localhost"
    },
    seleniumB: {
      desiredCapabilities: {
        browserName : 'chrome',
        chromeOptions : {
          w3c : false
        }
      },
      // リモートのwebdriverのipとportを指定する
      selenium_port :24444,
      selenium_host : "localhost"
    }
  }
};

function loadServices() {
  try {
    Services.seleniumServer = require('selenium-server');
  } catch (err) {}

  try {
    Services.chromedriver = require('chromedriver');
  } catch (err) {}

  try {
    Services.geckodriver = require('geckodriver');
  } catch (err) {}
}
